import "./globals.css";
import Nav from "@/components/navbar";
export const metadata = {
  title: "Next App 15",
  description: "Generated by create next app 15",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
